---
- hosts: all
  become: true
  gather_facts: no   #first install python2
  vars: 
    remote_server: 8.8.8.8
    remote_port: 5555

  tasks:
  - name: 'install python2'
    raw: apt -y install python

  - name: install openvpn
    apt: 
      name: openvpn 
      state: present

  - name: generate config.ovpn file
    template: 
      src: config.ovpn.j2
      dest: /etc/openvpn/config.ovpn



